// <auto-generated />
using System;
using BrandRiot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrandRiot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BrandRiotDbContext))]
    partial class BrandRiotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("riot")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrandRiot.Domain.Entities.Accounts.RiotAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstFetchedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastFetchedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSeenPlatform")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<string>("ResolvedCluster")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TagLine")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.HasIndex("GameName", "TagLine");

                    b.ToTable("riot_accounts", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lol.LolChampionMastery", b =>
                {
                    b.Property<string>("Puuid")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionLevel")
                        .HasColumnType("integer");

                    b.Property<long>("ChampionPoints")
                        .HasColumnType("bigint");

                    b.Property<long>("ChampionPointsSinceLastLevel")
                        .HasColumnType("bigint");

                    b.Property<long>("ChampionPointsUntilNextLevel")
                        .HasColumnType("bigint");

                    b.Property<bool>("ChestGranted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastPlayTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TokensEarned")
                        .HasColumnType("integer");

                    b.HasKey("Puuid", "ChampionId");

                    b.HasIndex("Puuid");

                    b.ToTable("lol_champion_masteries", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lol.LolLeagueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FreshBlood")
                        .HasColumnType("boolean");

                    b.Property<bool>("HotStreak")
                        .HasColumnType("boolean");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("SummonerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Veteran")
                        .HasColumnType("boolean");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Puuid", "QueueType")
                        .IsUnique();

                    b.ToTable("lol_league_entries", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lol.LolMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GameCreationUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameDurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameCreationUtc");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("lol_matches", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lol.LolMatchParticipant", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Puuid")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("CsTotal")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<long>("GoldEarned")
                        .HasColumnType("bigint");

                    b.Property<int>("Item0")
                        .HasColumnType("integer");

                    b.Property<int>("Item1")
                        .HasColumnType("integer");

                    b.Property<int>("Item2")
                        .HasColumnType("integer");

                    b.Property<int>("Item3")
                        .HasColumnType("integer");

                    b.Property<int>("Item4")
                        .HasColumnType("integer");

                    b.Property<int>("Item5")
                        .HasColumnType("integer");

                    b.Property<int>("Item6")
                        .HasColumnType("integer");

                    b.Property<int?>("KeystonePerk")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Summoner1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Summoner2Id")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<long>("TotalDamageDealtToChampions")
                        .HasColumnType("bigint");

                    b.Property<int>("VisionScore")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("MatchId", "Puuid");

                    b.HasIndex("ChampionId");

                    b.HasIndex("Puuid");

                    b.ToTable("lol_match_participants", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lol.Summoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<long>("RevisionDate")
                        .HasColumnType("bigint");

                    b.Property<string>("SummonerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SummonerLevel")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.ToTable("lol_summoners", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lor.LorMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cluster")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameFormat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("GameStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TotalTurnCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("lor_matches", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lor.LorMatchPlayer", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Puuid")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<string>("DeckCode")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("DeckId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FactionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("GameOutcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("OrderOfPlay")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "Puuid");

                    b.HasIndex("Puuid");

                    b.ToTable("lor_match_players", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lor.LorRankedLeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cluster")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cluster", "Rank");

                    b.ToTable("lor_ranked_leaderboard_entries", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Tft.TftLeagueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FreshBlood")
                        .HasColumnType("boolean");

                    b.Property<bool>("HotStreak")
                        .HasColumnType("boolean");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("SummonerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Veteran")
                        .HasColumnType("boolean");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Puuid", "QueueType")
                        .IsUnique();

                    b.ToTable("tft_league_entries", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Tft.TftMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cluster")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GameDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameLengthSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<string>("TftGameType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TftSetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("tft_matches", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Tft.TftMatchParticipant", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Puuid")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<string>("AugmentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CompanionContentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("GoldLeft")
                        .HasColumnType("integer");

                    b.Property<int>("LastRound")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Placement")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersEliminated")
                        .HasColumnType("integer");

                    b.Property<double>("TimeEliminatedSeconds")
                        .HasColumnType("double precision");

                    b.Property<long>("TotalDamageToPlayers")
                        .HasColumnType("bigint");

                    b.Property<string>("TraitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("UnitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("MatchId", "Puuid");

                    b.HasIndex("Puuid");

                    b.ToTable("tft_match_participants", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Tft.TftSummoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<long>("RevisionDate")
                        .HasColumnType("bigint");

                    b.Property<string>("SummonerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SummonerLevel")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.ToTable("tft_summoners", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Valorant.ValorantContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalizedNamesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentType", "ContentId")
                        .IsUnique();

                    b.ToTable("valorant_content_items", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Valorant.ValorantMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameLengthMillis")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GameStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("QueueId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("valorant_matches", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Valorant.ValorantMatchPlayer", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Puuid")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<string>("AbilityCastsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DamagePerRoundJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<long>("PlaytimeMillis")
                        .HasColumnType("bigint");

                    b.Property<int>("RoundsPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("MatchId", "Puuid");

                    b.HasIndex("Puuid");

                    b.ToTable("valorant_match_players", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Valorant.ValorantRankedEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfWins")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<int>("RankedRating")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Puuid", "ActId")
                        .IsUnique();

                    b.ToTable("valorant_ranked_entries", "riot");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lol.LolMatchParticipant", b =>
                {
                    b.HasOne("BrandRiot.Domain.Entities.Lol.LolMatch", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .HasPrincipalKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lor.LorMatchPlayer", b =>
                {
                    b.HasOne("BrandRiot.Domain.Entities.Lor.LorMatch", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .HasPrincipalKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Tft.TftMatchParticipant", b =>
                {
                    b.HasOne("BrandRiot.Domain.Entities.Tft.TftMatch", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .HasPrincipalKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Valorant.ValorantMatchPlayer", b =>
                {
                    b.HasOne("BrandRiot.Domain.Entities.Valorant.ValorantMatch", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .HasPrincipalKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lol.LolMatch", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Lor.LorMatch", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Tft.TftMatch", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("BrandRiot.Domain.Entities.Valorant.ValorantMatch", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
