<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>BrandRiot.Api</RootNamespace>
    <UserSecretsId>brandriot-api-dev</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrandRiot.Application\BrandRiot.Application.csproj" />
    <ProjectReference Include="..\BrandRiot.Infrastructure\BrandRiot.Infrastructure.csproj" />
  </ItemGroup>

</Project>
